[package]
name = "PasswordManager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
rusqlite = "0.28.0"
bcrypt = "0.10.0"

[[bin]]
name = "password-manager-cli"
path = "cli/main.rs"